providers = ["python"]

[phases.install]
cmds = [
  "python3 -m ensurepip --upgrade",
  "python3 -m pip install -r price_tracker/requirements.txt",
  "playwright install --with-deps chromium"
]

[phases.build]
cmds = ["cd price_tracker && python3 manage.py collectstatic --no-input"]
