[build]
builder = "nixpacks"

[deploy]
startCommand = "cd price_tracker && python3 manage.py migrate && gunicorn price_tracker.wsgi:application --bind 0.0.0.0:$PORT --workers 2"
healthcheckPath = "/"
restartPolicyType = "on_failure"
